/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TarotReadingService } from "../tarotReading.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TarotReadingCreateInput } from "./TarotReadingCreateInput";
import { TarotReading } from "./TarotReading";
import { TarotReadingFindManyArgs } from "./TarotReadingFindManyArgs";
import { TarotReadingWhereUniqueInput } from "./TarotReadingWhereUniqueInput";
import { TarotReadingUpdateInput } from "./TarotReadingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TarotReadingControllerBase {
  constructor(
    protected readonly service: TarotReadingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TarotReading })
  @nestAccessControl.UseRoles({
    resource: "TarotReading",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTarotReading(
    @common.Body() data: TarotReadingCreateInput
  ): Promise<TarotReading> {
    return await this.service.createTarotReading({
      data: data,
      select: {
        cards: true,
        createdAt: true,
        date: true,
        id: true,
        question: true,
        result: true,
        spreadType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TarotReading] })
  @ApiNestedQuery(TarotReadingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TarotReading",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tarotReadings(@common.Req() request: Request): Promise<TarotReading[]> {
    const args = plainToClass(TarotReadingFindManyArgs, request.query);
    return this.service.tarotReadings({
      ...args,
      select: {
        cards: true,
        createdAt: true,
        date: true,
        id: true,
        question: true,
        result: true,
        spreadType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TarotReading })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TarotReading",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async tarotReading(
    @common.Param() params: TarotReadingWhereUniqueInput
  ): Promise<TarotReading | null> {
    const result = await this.service.tarotReading({
      where: params,
      select: {
        cards: true,
        createdAt: true,
        date: true,
        id: true,
        question: true,
        result: true,
        spreadType: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TarotReading })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TarotReading",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTarotReading(
    @common.Param() params: TarotReadingWhereUniqueInput,
    @common.Body() data: TarotReadingUpdateInput
  ): Promise<TarotReading | null> {
    try {
      return await this.service.updateTarotReading({
        where: params,
        data: data,
        select: {
          cards: true,
          createdAt: true,
          date: true,
          id: true,
          question: true,
          result: true,
          spreadType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TarotReading })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TarotReading",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTarotReading(
    @common.Param() params: TarotReadingWhereUniqueInput
  ): Promise<TarotReading | null> {
    try {
      return await this.service.deleteTarotReading({
        where: params,
        select: {
          cards: true,
          createdAt: true,
          date: true,
          id: true,
          question: true,
          result: true,
          spreadType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
